import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




type Repository = {
  id: number;
  title: string;
  
}







export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
        const res = await fetch('https://laravel.distribuidoravega.cl/wp-json/wp/v2/posts/');
        const data = await res.json();
        console.log(data)
       return (
    
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
  
}
